% -------------------------------------------------------------------
%  Generated by MATLAB on 27-Nov-2017 18:17:32
%  MATLAB version: 9.3.0.713579 (R2017b)
% -------------------------------------------------------------------
saveVarsMat = load('prors.mat');

ROI = saveVarsMat.ROI; % <1x1 struct> too many elements at ROI.coordinates{1}

ans = true;

data = saveVarsMat.data; % <1x1 struct> too many elements at data.Im1

max_time = 30;

pl = saveVarsMat.pl; % <1x1 COM.PrairieLink_Application> unsupported class

clear saveVarsMat;
